# Generated by Django 4.0.1 on 2022-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.DateField()),
                ('cnt', models.IntegerField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'train_data',
                'managed': False,
            },
        ),
    ]
