# Generated by Django 4.0.1 on 2022-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squat',
        ),
    ]
