# Generated by Django 3.2.11 on 2022-01-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, null=True)),
                ('member_name', models.CharField(max_length=50, null=True)),
                ('psw_rg', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
    ]
