# Generated by Django 3.2.11 on 2022-01-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('history', '0002_rename_name_history_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
    ]
