# Generated by Django 3.2.11 on 2022-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
