# Generated by Django 3.2.11 on 2022-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
    ]
