# Generated by Django 4.0.1 on 2022-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pullup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='shoulder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='squat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='triceps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='vrksasana',
            field=models.IntegerField(default=0),
        ),
    ]
