# Generated by Django 4.0.1 on 2022-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0013_alter_history_pullup_alter_history_shoulder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
